# Generated by Django 5.2.6 on 2025-10-02 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], db_index=True, default='en_attente', max_length=20)),
                ('adresse_livraison', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('date_livraison_souhaitee', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_production', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='production.commande')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('methode', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('virement', 'Virement'), ('cash', 'Espèces')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], db_index=True, default='en_attente', max_length=20)),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='production.commande')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evaluations/%Y/%m/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='production.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(db_index=True, max_length=100)),
                ('type_production', models.CharField(choices=[('fruits', 'Fruits'), ('legumes', 'Légumes'), ('cereales', 'Céréales'), ('tubercules', 'Tubercules'), ('elevage', 'Élevage'), ('produits_transformes', 'Produits Transformés')], db_index=True, max_length=30)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unite_mesure', models.CharField(choices=[('kg', 'Kilogramme'), ('tonne', 'Tonne'), ('unite', 'Unité'), ('litre', 'Litre'), ('sac', 'Sac')], max_length=20)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('adresse_complete', models.TextField()),
                ('disponible', models.BooleanField(db_index=True, default=True)),
                ('date_recolte', models.DateField()),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('certification', models.CharField(choices=[('bio', 'Bio'), ('standard', 'Standard'), ('agroecologique', 'Agroécologique')], default='standard', max_length=20)),
                ('description', models.TextField()),
                ('conditions_stockage', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='users.producteur')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productions/%Y/%m/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='production.production')),
            ],
            options={
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='production.production'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['produit', 'disponible'], name='production__produit_5ba0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['type_production', 'disponible'], name='production__type_pr_282769_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['producteur', 'disponible'], name='production__product_9db3b2_idx'),
        ),
        migrations.AddIndex(
            model_name='production',
            index=models.Index(fields=['-date_creation'], name='production__date_cr_e6be0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='photoproduction',
            constraint=models.CheckConstraint(condition=models.Q(('ordre__lte', 4)), name='max_5_photos'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['client', '-date_creation'], name='production__client__c7d892_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['production', '-date_creation'], name='production__product_f2676e_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', '-date_creation'], name='production__statut_9ec4ca_idx'),
        ),
    ]
