version: "3.9"

services:
  digitagro_api:
    build: .
    container_name: digitagro_api
    ports:
      - "8001:8000"
    volumes:
      - .:/app:cached
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: always
    env_file:
      - .env
    environment:
      - DJANGO_ALLOWED_HOSTS=185.217.125.37,localhost,127.0.0.1
      - DB_HOST=185.217.125.37
      - DB_PORT=5432
      - DB_NAME=digitagro_db
      - DB_USER=digitagro
      - DB_PASSWORD=Digitagro@2002
      - REDIS_HOST=redis  # ← Nouveau
      - REDIS_PORT=6379   # ← Nouveau
    depends_on:
      - redis  # ← Nouveau
    networks:
      - digitagro_network

  # ← Ajouter Redis
  redis:
    image: redis:7-alpine
    container_name: digitagro_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - digitagro_network
    restart: always

volumes:
  static_volume:
  media_volume:
  redis_data:  # ← Nouveau

networks:
  digitagro_network:
    driver: bridge