# Generated by Django 5.2.6 on 2025-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consommateur',
            options={'verbose_name': 'Profil Consommateur', 'verbose_name_plural': 'Profils Consommateurs'},
        ),
        migrations.AlterModelOptions(
            name='distributeur',
            options={'verbose_name': 'Profil Distributeur', 'verbose_name_plural': 'Profils Distributeurs'},
        ),
        migrations.AlterModelOptions(
            name='producteur',
            options={'verbose_name': 'Profil Producteur', 'verbose_name_plural': 'Profils Producteurs'},
        ),
        migrations.AlterModelOptions(
            name='transformateur',
            options={'verbose_name': 'Profil Transformateur', 'verbose_name_plural': 'Profils Transformateurs'},
        ),
        migrations.AlterModelOptions(
            name='transporteur',
            options={'verbose_name': 'Profil Transporteur', 'verbose_name_plural': 'Profils Transporteurs'},
        ),
        migrations.AddField(
            model_name='consommateur',
            name='total_commandes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='distributeur_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_consommateur',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_distributeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_distributeur_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_producteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_producteur_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_transformateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_transformateur_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_transporteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_transporteur_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='producteur_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transformateur_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transporteur_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='last_production_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='total_productions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='note_moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='transporteur',
            name='total_trajets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consommateur',
            name='adresse_livraison',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='consommateur',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_choisi',
            field=models.CharField(blank=True, help_text='DEPRECATED - Utiliser les booléens is_*', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='licence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='type_distribution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='distributeur',
            name='zones_service',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='type_production',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='capacite_traitement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transformateur',
            name='type_transformation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='capacite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='permis_transport',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transporteur',
            name='type_vehicule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['telephone'], name='users_custo_telepho_b5f784_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_producteur'], name='users_custo_is_prod_c02fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_transporteur'], name='users_custo_is_tran_10b401_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['-created_at'], name='users_passw_created_26a77c_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['user', 'is_validated'], name='users_passw_user_id_416c49_idx'),
        ),
    ]
