# Generated by Django 5.2.6 on 2025-10-20 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_consommateur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Numéro à vérifier (format international)', max_length=20)),
                ('code', models.CharField(help_text='Code 5 chiffres', max_length=5)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Expiration 5 minutes')),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('attempts', models.IntegerField(default=0, help_text='Nombre de tentatives de vérification')),
                ('twilio_sid', models.CharField(blank=True, help_text='ID message Twilio', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vérification Téléphone',
                'verbose_name_plural': 'Vérifications Téléphone',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('phone_verified', '📱 Téléphone Vérifié'), ('documents_verified', '✅ Documents Vérifiés'), ('organization_member', '🏢 Membre GIC/Coopérative'), ('top_seller', '⭐ Top Vendeur'), ('lightning_fast', '⚡ Livraison Express'), ('veteran', '🎖️ Vétéran'), ('trusted_partner', '🤝 Partenaire de Confiance')], db_index=True, max_length=50)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration (si badge temporaire)", null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires (ex: nombre de ventes pour top_seller)')),
            ],
            options={
                'verbose_name': 'Badge Utilisateur',
                'verbose_name_plural': 'Badges Utilisateurs',
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_sms_attempt',
            field=models.DateTimeField(blank=True, help_text="Dernière tentative d'envoi SMS", null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Téléphone vérifié par SMS'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Date de vérification du téléphone', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_attempts_count',
            field=models.IntegerField(default=0, help_text="Nombre de tentatives d'envoi SMS"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='cooperative_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom de la coopérative'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='cooperative_registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro d'enregistrement coopérative"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='gic_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du GIC'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='gic_registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro d'enregistrement GIC"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='is_in_cooperative',
            field=models.BooleanField(default=False, verbose_name="Membre d'une coopérative agricole"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='is_in_gic',
            field=models.BooleanField(default=False, help_text="Groupement d'Intérêt Communautaire", verbose_name="Membre d'un GIC"),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone_verified'], name='users_custo_phone_v_da7f55_idx'),
        ),
        migrations.AddField(
            model_name='phoneverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='awarded_by',
            field=models.ForeignKey(blank=True, help_text='Admin qui a attribué le badge (si manuel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['phone_number', 'verified'], name='users_phone_phone_n_f421e7_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['expires_at'], name='users_phone_expires_060708_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneverification',
            index=models.Index(fields=['user', '-created_at'], name='users_phone_user_id_c5ec12_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'is_active'], name='users_userb_user_id_2da62d_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['badge_type', 'is_active'], name='users_userb_badge_t_eb6b99_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge_type')},
        ),
    ]
