# Generated by Django 5.2.6 on 2025-10-02 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_order', '📋 Nouvelle commande'), ('payment_received', '💰 Paiement reçu'), ('order_confirmed', '✅ Commande confirmée'), ('product_shipped', '📦 Produit expédié'), ('delivery_completed', '✅ Livraison effectuée'), ('new_review', '⭐ Nouvelle évaluation'), ('transport_request', '🚚 Demande de transport'), ('transport_confirmed', '✅ Transport confirmé'), ('transport_started', '📍 Transport démarré'), ('transport_arrived', '🎯 Transport arrivé'), ('transformation_request', '🏭 Demande transformation'), ('transformation_completed', '✅ Transformation terminée'), ('products_ready', '📦 Produits prêts'), ('stock_updated', '📦 Stock mis à jour'), ('bulk_order', '💼 Commande en gros'), ('new_message', '💬 Nouveau message'), ('new_device', '🔒 Nouvelle connexion'), ('password_changed', '🔑 Mot de passe modifié'), ('profile_incomplete', '⚠️ Profil incomplet'), ('delivery_delayed', '⚠️ Retard livraison'), ('order_cancelled', '❌ Commande annulée'), ('refund_requested', '💰 Remboursement demandé')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
